### ISSUE TITLE
of_bytes?

### ISSUE THREAD

**Issue by dsheets** [mirage/ocaml-cstruct#103]
What is the best way to take a `Bytes.t` and get it into a `Cstruct.t`?

The best I know of right now is `Cstruct.of_string (Bytes.to_string bytes)` which copies unnecessarily and is quite clumsy. Is there a better way? Should there be an `of_bytes` in the interface?

**Comment by hannesm** [comment]
`Bytes.to_string` doesn't copy, but is `%identity`...  but I agree that there should be an explicit `of_bytes`

**Comment by dsheets** [comment]
From <https://github.com/ocaml/ocaml/blob/trunk/stdlib/bytes.ml#L55>:
```ocaml
let to_string b = unsafe_to_string (copy b)
```

Unless `copy` doesn't copy, I think it copies.

**Comment by hannesm** [comment]
ups, you are right. sorry.

**Comment by dbuenzli** [comment]
@dsheets `Bytes.unsafe_to_string` but of course `cstruct` should not encourage you to use unsafe functions so it seems an `of_bytes` is needed.
