### ISSUE TITLE
Build assumes the existence of lwt.unix when lwt is installed.

### ISSUE THREAD

**Issue by camlspotter** [mirage/ocaml-cstruct#113]
cstruct.2.3.0 build fails in MinGW OCaml when lwt is installed.  It seems that cstruct assumes the existence of lwt.unix.  In MinGW OCaml, lwt does not install lwt.unix.

The workaround for cstruct.2.3.0 in MinGW OCaml + lwt is pretty simple: drop the line of `<lwt/*.ml{,i,y}>: pkg_lwt.unix` from the file `_tag`.  It would be nice if the build checks lwt.unix.

It would be nice if future releases of cstruct checks lwt.unix is installed or not.

**Comment by camlspotter** [comment]
I guess the right fix is to fix `configure` so that it checks `lwt.unix` rather than `lwt`.

**Comment by yomimono** [comment]
Thanks for the report, @camlspotter.  We'll try to get this sorted soon.

**Comment by yomimono** [comment]
@avsm, am I correct in concluding this should be fixed by #115 ?

**Comment by avsm** [comment]
yes, it should already be in ocaml/opam-repository#7740, so released versions should work.

**Comment by yomimono** [comment]
@camlspotter, please let us know if you notice further brokenness, and thanks for the report!
