### ISSUE TITLE
feature request: random, valid cenums?

### ISSUE THREAD

**Issue by yomimono** [mirage/ocaml-cstruct#114]
I frequently find myself wanting to generate a random, but valid, cenum for testing that my code behaves correctly with potentially strange inputs.  I'd like it if `cstruct.ppx` could help me by generating a `random_cenum` (just as there are `int_to_cenum` `string_to_cenum` functions generated) that chooses between the valid options.

**Comment by avsm** [comment]
Is there some sort of quickcheck library that you are using that gives us a convention for what to expose? I'm thinking of the equivalent of an `Alcotest.TESTABLE`

**Comment by yomimono** [comment]
I abandoned [arbitrary-network](https://github.com/yomimono/arbitrary-network) some time ago, but that was basically an attempt to solve this problem a layer up relying on both `cstruct` and the `quickcheck` available in the default opam repository.

**Comment by yomimono** [comment]
This is somewhat solved with `crowbar` and `ppx_to_crowbar`, so I'm happy to close this issue.
