### ISSUE TITLE
feature request: generate enum_of_int: int -> (enum, msg) result, and deprecate int_to_enum : int -> enum option

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-cstruct#118]
then it would compose nicely with Rresult..

**Comment by avsm** [comment]
This would a breaking change, but one that's worth doing with a major version bump I think.  It would be reduce the amount of information lost in error messages...

**Comment by hannesm** [comment]
On 09/07/2017 12:59, Anil Madhavapeddy wrote:
> This would a breaking change, but one that's worth doing with a major version bump I think.  It would be reduce the amount of information lost in error messages...

A possible more smooth migration path:
- at version cstruct-ppx.X.Y.(Z+1), generate ``a_of_int : int -> (a, [>
`Msg of string ]) result`` and mark `int_to_a` deprecated for all
`[%%cenum a]` occurences
- at version cstruct-ppx.(X+1), do not generate any `int_to_a` bindings
anymore.

There is already some inconsistency between various libraries whether
the name should be `x_to_a` or `a_of_x`:
- Pervasives provides `int_of_string` and `string_of_int` (i.e. always `of`)
- `Int64` (and other modules) provide `to_int` and `of_int`
- `sexplib` provides `sexp_of_a`, `a_of_sexp` (i.e. always `of`)
- `cstruct` always uses `to`: `int_to_a`, `a_to_int`

IMHO using `a_` as a prefix for these conversion functions is easier to
read and comprehend - with `int_to_a`, I've to skip to the last word of
the binding to discover what it is doing, with `a_of_int` I can
immediately discover that I may get an `a`.

[But likely this naming is a subjective matter, and so others will have
other opinions, nevertheless the above proposed smooth transition would
be beneficial over a major version breaking change and a disconnected
universe - it is easier to introduce new bindings and deprecate existing
ones than to change the semantics of existing ones.]

**Comment by hannesm** [comment]
closing due to (a) lack of interest / activity in the past 6 years (b) I moved on, and ppx_cstruct is gone from my dependency cone (and won't come back).
