### ISSUE TITLE
remove camlp4 dependency via ocplib-endian

### ISSUE THREAD

**Issue by avsm** [mirage/ocaml-cstruct#122]
ocplib-endian depends on cppo which depends on camlp4.

I think we dont need the abstraction provided by ocplib-endian any more, as our minimum compiler version can safely be 4.02.3 upwards.  Creating this issue to see how invasive that patch would be...

**Comment by yminsky** [comment]
Doesn't cppo use camlp4?

**Comment by avsm** [comment]
Weird, I also checked it before creating the issue and thought that cppo used camlp4. I guess I was confusing it with optcomp, which older ocplib-endian uses.  If you had an older version of ocplib-endian pulled in due to a constraint, you might have seen camlp4 @yminsky
