### ISSUE TITLE
Incorrect version constraints specified

### ISSUE THREAD

**Issue by sgrove** [mirage/ocaml-cstruct#135]
Ran into this trying to build a switch that relies on `ocaml-graphql-server` and `reason`. The problem comes up when installing cohttp transitively, I believe, ultimately with cstruct fails to build because `#  Error: No implementations provided for the following modules: Ast_404 referenced from /Users/s/.opam/ribbit2/lib/ppx_tools_versioned/ppx_tools_versioned.cmxa(Ast_convenience_404)`

Here's a gist with the full output: https://gist.github.com/sgrove/f7a7a96555a804352467dff06d748ed8

I was told it's because of mis-specified version constraints, but I'm not sure *which* are mis-specified. Perhaps @jordwalke or @rgrinberg might have some idea?

**Comment by rgrinberg** [comment]
cc'ing @let-def

**Comment by let-def** [comment]
@sgrove what is the output of `ocamlfind ocamlopt -only-show -linkpkg -g -linkpkg -package bigarray -package ppx_tools_versioned.metaquot_404 -package ocaml-migrate-parsetree -I ppx ppx/ppx_cstruct.cmx ppx/standalone.cmx -o ppx/standalone.native` ?

**Comment by let-def** [comment]
@sgrove try after `opam upgrade ppx_tools_versioned` (you should have beta version at least).

**Comment by let-def** [comment]
Arf... It's `reason-parser` which pinned alpha version.

**Comment by jordwalke** [comment]
@let-def want to upgrade `reason-parser`? Happy to accept the PR and you can also push an opam update.

**Comment by ryyppy** [comment]
@let-def we are experiencing the same problem, but with `cohttp` or `conduit` ... all of those are breaking on `opam install`... any idea how we can circumvent that temporarily?

**Comment by let-def** [comment]
@ryyppy what is your version of `ppx-tools-versioned`? It should be at least 5.0beta.

**Comment by jordwalke** [comment]
I have `ppx_tools_versioned        5.0alpha` installed, and cstruct fails to install. No reason installed at all. I think that cstruct must specify a constraint on its versions `>= 5.0beta`

**Comment by rgrinberg** [comment]
I think https://github.com/mirage/ocaml-cstruct/pull/136 needs to be merged.

@avsm @samoht can we merge and release that fix?

**Comment by jordwalke** [comment]
Also the two outstanding PRs to opam for Reason and Reason parser should fix it. Thanks!

**Comment by sgrove** [comment]
Has a new version been pushed that fixes this? We're still running into issues with it, and not sure what to pin/checkout to get past it for now.

**Comment by avsm** [comment]
@sgrove I think this should now be fixed in stable opam-repository; are you still seeing it?

**Comment by sgrove** [comment]
I pinned to some combination of masters and the issue went away, so if stable opam was updated then it should presumably work - thank you!

**Comment by sgrove** [comment]
I pinned to some combination of masters and the issue went away, so if stable opam was updated then it should presumably work - thank you!

**Comment by avsm** [comment]
Thanks -- to stop this sort of thing happening in the future, .we've now got revdeps testing in-place in opam-repository, and are also [migrating away from the use of depopts](http://rgrinberg.com/posts/optional-dependencies-considered-harmful/) to help reduce the complexity of testing cases like this.
