### ISSUE TITLE
Crash in cstub for check_alignment_bigstring

### ISSUE THREAD

**Issue by cfcs** [mirage/ocaml-cstruct#140]
When you pass a `0` argument to `check_alignment` the process crashes due to a division-by-zero error in the c stub.

.mli:
```ocaml
val check_alignment : t -> int -> bool
(** [check_alignment cstr alignment] is [true] if the first byte stored
    within [cstr] is at a memory address where [address mod alignment = 0],
    [false] otherwise.
    Typical uses are to check a buffer is aligned to a page or disk sector
    boundary. *)
```

cstruct.ml:
```ocaml
external check_alignment_bigstring : buffer -> int -> int -> bool = "caml_check_alignment_bigstring"

let check_alignment t alignment = check_alignment_bigstring t.buffer t.off alignment
```

cstruct_stubs.c:
```c
CAMLprim value
caml_check_alignment_bigstring(value val_buf, value val_ofs, value val_alignment)
{
  uint64_t address = (uint64_t) (Caml_ba_data_val(val_buf) + Long_val(val_ofs));
  int alignment = Int_val(val_alignment);
  return Val_bool(address % alignment == 0);
}
```

When `val_alignment` is `0` this crashes the program.

**Comment by cfcs** [comment]
By the way, I am curious as to why it adds the `Long_val(val_ofs)`. Are there scenarios where t.off is not 0?

**Comment by avsm** [comment]
Reproduced and test case added in 86216e878a3952993e512572419e33c7c4859d03

**Comment by avsm** [comment]
> Are there scenarios where t.off is not 0

For multi-page cstructs the t.off might be >0 -- and we can use this function to test if the specific cstruct view is page-aligned with respect to the underlying memory.

**Comment by cfcs** [comment]
Aha, okay!
