### ISSUE TITLE
ppx not working with lwt

### ISSUE THREAD

**Issue by andrewray** [mirage/ocaml-cstruct#148]
Is it correct to have the file standalone.ml built into the ppx library for jbuilder (as it appears to be)?

The lwt syntax extension isn't playing nice with cstruct.  

cc @diml

**Comment by diml** [comment]
Nope, it shouldn't be there indeed. I was actually looking at this as well as someone asked me about it. There is a fix in #150

**Comment by andrewray** [comment]
Ta.  Closing as addressed in #149 and #150
