### ISSUE TITLE
Documentation: Missing `@raise` for `split`

### ISSUE THREAD

**Issue by cfcs** [mirage/ocaml-cstruct#166]
The `split` function is missing a warning about exceptions thrown:
```
utop # Cstruct.split Cstruct.(create 2) 3;;
Exception: Invalid_argument "Cstruct.split [0,2](2) start=0 off=3".
```

**Comment by cfcs** [comment]
(It would be nice to have an interface with `result` wrappers around the exception stuff)

**Comment by avsm** [comment]
see #118 for another `result` request

**Comment by cfcs** [comment]
Ah, very nice!
