### ISSUE TITLE
hexdump_pp_to_buffer

### ISSUE THREAD

**Issue by cfcs** [mirage/ocaml-cstruct#167]
This interface seems a little bit incoherent:
```
  val Cstruct.hexdump t -> unit                                                 (* pp to stdout (not stderr) *)
  val Cstruct.hexdump_to_buffer Buffer.t -> t -> unit                (* pp to Buffer.t *)
  val Cstruct.hexdump_pp Format.formatter -> t -> unit           (* pp with custom formatter to Cstruct.t *)
```
I would expect there to be a `hexdump_pp_to_buffer` OR a `hexdump_to_t` function (and that `hexdump` would output to the user's channel of choice rather than stdout, but that's a breaking API change).

**Comment by avsm** [comment]
we could deprecate `hexdump` with an annotation -- it was just a debugging function in the early interfaces.

I don't think you need a hexdump_pp_to_buffer as you can define a formatter that does that (see Format.formatter_of_buffer).
