### ISSUE TITLE
4.06 support for cstruct?

### ISSUE THREAD

**Issue by gasche** [mirage/ocaml-cstruct#180]
opam-builder currently reports:

```
Unsupported OCaml version 4.06.0+beta2
E: Failure("Command 'sh select_ppx_version.sh conf' terminated with error code 1")
[ERROR] The compilation of cstruct failed at "./configure --prefix /home/barsac/scherer/opam-builder/4.06.0+beta2+default-unsafe-string/.opam/4.06.0+beta2+default-unsafe-string --disable-lwt --disable-ppx --disable-async --enable-unix".
```

**Comment by hannesm** [comment]
which version of cstruct is that, though? since `cstruct.2.3.3`, `ocaml-migrate-parsetree` is used, and the `select_ppx_version.sh` was removed.

**Comment by gasche** [comment]
Indeed, sorry -- I forgot to look at the version. I expect that this will be fixed by @seliopou's https://github.com/ocaml/opam-repository/pull/10286/commits/37bb7aaf5b223d49667c03fffabb4c1d5458fbbd .
