### ISSUE TITLE
Compilation of cstruct-lwt fails

### ISSUE THREAD

**Issue by qbi** [mirage/ocaml-cstruct#181]
I'm trying to build [jackline](https://github.com/hannesm/jackline). One requirement is cstruct-lwt v3.1.1. However building jackline fails on cstruct-lwt. So I tried `opam install --debug cstruct-lwt`. However besides some seemingly irrelevant messages (tar, mv, rm etc.) it only shows this error message:

> [ERROR] The compilation of cstruct-lwt failed at "jbuilder build -p cstruct-lwt -j 4".

The stdout- and stderr files are empty. I'm using opam 1.2.2.
What can cause this error? Can I provide more relevant information?

**Comment by hannesm** [comment]
when `opam install cstruct-lwt` fails, it will leave some output in your `~/.opam/XX/build/cstruct-lwt` directory, namely a `.out`, `.env` and `.err` - would you mind pasting the contents of these?  also, the output of `opam config list` would be useful.  Which operating system are you on?  did you install a fresh OCaml (by doing `opam switch XX`) or use the system provided one?

**Comment by qbi** [comment]
I'm using Debian sid and did a `opam switch 4.04.0` before (according to my shell history and to `opem switch`). I switched to system which is 4.05.0 and ran `opam install cstruct-lwt` successfully.

> ∗  installed cstruct-lwt.3.1.1
> Done.
> =-=- lwt.3.1.0 installed successfully -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=           
> …

However I continued with `opem install jackline` and the system wanted to recompile `lwt` and `cstruct-lwt`:

>          ↻  recompile lwt                   3.1.0        [uses camlp4] 
>          ↻  recompile cstruct-lwt           3.1.1        [uses lwt]    

This led to an error:
> === ERROR while installing lwt.3.1.0 =========================================

As far as I can tell this is related to `lwt`. So I will a report over there (see https://github.com/ocsigen/lwt/issues/488) and also provide the information you requested. So I assume this report can be closed.

**Comment by hannesm** [comment]
@qbi thanks for the investigation.  may it be that you forgot a `` eval `opam config env` `` (just after `opam switch xxx`) in the shell where you do `opam install jackline`?

**Comment by qbi** [comment]
Well, I had some issues with `eval …`, but then I realized that `eval` is a shell-builtin. :-)
However now `opam switch` doesn't state that my environment is not in sync. So I assume everything is OK. The install still fails with `lwt`. I left all information I could gather at the referenced report.

**Comment by avsm** [comment]
This is likely because you are using a version of opam compiled with ocaml 4.05.0, which has a known bug that requires you to do an eval to get the right PATH.

**Comment by hannesm** [comment]
@qbi I'll close this since as far as I understand this works for you now, and you reported the issue upstream.  Please reopen and report here if I'm wrong.
