### ISSUE TITLE
Cstruct.len

### ISSUE THREAD

**Issue by vbmithr** [mirage/ocaml-cstruct#199]
The rest of the world uses `length` and not `len`, also, it happens that I locally open `Cstruct` and use `len` values to store an integer, which causes a clash with `Cstruct.len` and I spent sometimes to understand the issue. I kinda get used to know `Cstruct.len` but I really think it should be renamed to be consistent with OCaml (stdlib, Core, etc) convention.

**Comment by hannesm** [comment]
I agree (and added the `API break` label here), esp. for consideration if we decide to have a new major version (in the meantime, we can have a grace period where both `length` and `len` is provided, but `len` is marked as deprecated).

**Comment by avsm** [comment]
sounds good to me.

**Comment by hannesm** [comment]
thanks to @dinosaure in #237 there's now `Cstruct_cap.length`, the new interface. I suggest we leave the old as is and deprecate it once we switched over to the capabilities interface.
