### ISSUE TITLE
of_sub_string etc

### ISSUE THREAD

**Issue by cfcs** [mirage/ocaml-cstruct#200]
We currently have these functions for initializing a new Cstruct:
```ocaml
  val Cstruct.of_bigarray ?off:int -> ?len:int -> buffer -> t
```
and
```ocaml
  val Cstruct.of_string ?allocator:(int -> t) -> string -> t
  val Cstruct.of_bytes ?allocator:(int -> t) -> bytes -> t
  val Cstruct.of_hex string -> t
```
It would be nice, and would seem more consistent, if it would be possible to construct a `Cstruct.t` directly from a slice of a `string`/`bytes` (like you can with `of_bigarray`) instead of having to first do a `String.sub`/`Bytes.sub` (which means a redundant memcpy operation) before the copy into the new `Cstruct.t`.

Also, why is there no `?allocator` for `of_bigarray`? Is that because it doesn't actually copy, but maps to the same memory? If so, that should probably be documented?

**Comment by XVilka** [comment]
@cfcs slicing was added, can this one be closed then?

**Comment by cfcs** [comment]
Yes, thanks!

**Comment by cfcs** [comment]
(I guess the `?allocator` question is still relevant, but I have forgotten why I cared when I reported this)
