### ISSUE TITLE
Cstruct.blit_from_string uses bytes?

### ISSUE THREAD

**Issue by samoht** [mirage/ocaml-cstruct#202]
In version 3.2.1, [blit_to_string](https://github.com/mirage/ocaml-cstruct/blob/master/lib/cstruct.mli#L334) has the wrong signature:

```
val blit_to_string: t -> int -> bytes -> int -> int -> unit
```

We should either remove that (deprecated) function or provides something which actually uses a string, even if I don't know exactly what that means in this case. Probably something like `unsafe_blit_to_string`?

**Comment by emillon** [comment]
`blit_to_string` is marked as a deprecated (since 2015) alias to `blit_to_bytes`, so I think it's safe to delete.

**Comment by XVilka** [comment]
So this one can be closed, right?

**Comment by emillon** [comment]
Yes, I think so!

**Comment by hannesm** [comment]
the `@deprecated` ocamldoc attribute didn't lead to OCaml compiler warnings, also `blit_to_string` is still used [quite a bit](https://github.com/search?q=Cstruct.blit_to_string&type=Code). I'd propose to merge #251 which uses `[@@ocaml.deprecated]` and remove that function from the next major version. WDYT?

**Comment by hannesm** [comment]
now that #251 is merged, I'll close this issue. thanks for the report!
