### ISSUE TITLE
Add cstruct.js as a runtime file

### ISSUE THREAD

**Issue by copy** [mirage/ocaml-cstruct#203]
Dune supports a mechanism to automatically find and link the JavaScript dependencies of libraries, so one doesn't need to specify `+cstruct/cstruct.js` manually.

See `(javascript_files (<files-list>))`: https://dune.readthedocs.io/en/latest/dune-files.html#js-of-ocaml

**Comment by avsm** [comment]
This one's in cstruct 4.0.0
