### ISSUE TITLE
Support bi-endian struct definitions

### ISSUE THREAD

**Issue by XVilka** [mirage/ocaml-cstruct#206]
Currently Cstruct allows to declare either big-endian or little-endian structures with corresponding getters and setters. Would be really handy to support also `[@@bi-endian]` attribute to generate both. Or maybe any better way for structures that can handle both endians.

**Comment by avsm** [comment]
Out of curiosity, what for?

**Comment by XVilka** [comment]
For example in embedded file formats can have the same format structure, but without defined endianess. So program should be able to parse the same structure in both big endian and little endian for different files.

**Comment by avsm** [comment]
That's true -- I believe pcap defines the endianness at the start of the file.

**Comment by XVilka** [comment]
@samoht any suggestions on how to proceed? Because I cannot use the same name as with big-endian/little-endian, I had to provide different function names or wrap them into the module. What is the preferred approach?

**Comment by samoht** [comment]
No strong opinion on the names but I guess using `BE` and `LE` modules like in [ocplib-endian](https://github.com/OCamlPro/ocplib-endian) would make sense.

**Comment by XVilka** [comment]
Fixed in https://github.com/mirage/ocaml-cstruct/commit/554aa364401832c94db5c89ea8ddda195b12eb47
