### ISSUE TITLE
Automatically form records of the types?

### ISSUE THREAD

**Issue by XVilka** [mirage/ocaml-cstruct#214]
Have you considered to automatically generate the proper OCaml records for nicer field access?

I suggest something like:
```ocaml
[%%cstruct
type mytype = {
  field_a: int16_t [@outtype int];
  field_b: int64_t;
  field_c: int32_t [@outtype int32];
} [@@big_endian]
]
```
would generate also
```ocaml
type mytype_out = {
     field_a: int;
     field_c: int32 array;
}

let make_mytype_out cs_buf =
    {
       field_a  = get_mytype_field_a cs_buf;
       field_c = get_mytype_field_c cs_buf;
    }
```

**Comment by avsm** [comment]
Not introducing new types was one of the original design intentions of this library -- it was to pull out views from existing external memory structures, and not to introduce new memory layouts (which a record type would).  So while it's possibly in scope to define constructor functions that would initialise a Bigarray, I consider it out of scope for Cstruct to allocate a new boxed record layout.  This may change in future OCaml releases as we gain more control over memory layout (see e.g. [Stephen Dolan's talk on this recently](https://www.janestreet.com/tech-talks/unboxed-types-for-ocaml/))
