### ISSUE TITLE
sexplib dependency

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-cstruct#222]
can we make the sexplib dependency optional (similar to how it was done in uri and ipaddr)!? thanks //cc @avsm (this is first for the main cstruct package, but same would be nice for the ppx_cstruct package - see #116).

**Comment by avsm** [comment]
Yes, this is fine by me. will do in a separate major rev

**Comment by avsm** [comment]
@TheLortex also requests this for mirage/mirage#969 simplification
