### ISSUE TITLE
Many unused values are created (warning 32)

### ISSUE THREAD

**Issue by emillon** [mirage/ocaml-cstruct#225]
Hi,

A [%%cstruct type ...] declaration creates many declarations, potentially unused. It is common in many ppxs to generate warning-free code. In particular, many projects that use `ppx_cstruct` seem to locally suppress these warnings.

What do you think about adding `let _ = set_x` etc declarations? I'm happy to provide a patch. Thanks!

**Comment by avsm** [comment]
Is this fixed if we switch to ppxlib? Patches to fix this are very welcome. It’s a pity if we need top level module initialisers for this - is having a warning -3 attribute around the generated code not enough?

**Comment by emillon** [comment]
I don't think it's directly taken care of by ppxlib.

Adding attributes would work as well, but does `let _ = something` still exist at link-time?
