### ISSUE TITLE
ppx tests - do they run?

### ISSUE THREAD

**Issue by emillon** [mirage/ocaml-cstruct#226]
Hi,

I noticed that ppx tests are built, but not executed. They define a main function, but it does not run:

https://github.com/mirage/ocaml-cstruct/blob/b30ec693e1218bc3e1b3333259312f4555300b88/ppx_test/pcap.ml#L173

Is this intended? otherwise I can set up a test harness and a `.expected` file so that we can compare the output.

Let me know what you think. Thanks!

**Comment by avsm** [comment]
The original intention was to make sure they compile — it should do no harm to run them as well indeed :)
