### ISSUE TITLE
ppx: do not emit code for unused fields

### ISSUE THREAD

**Issue by emillon** [mirage/ocaml-cstruct#230]
Hi,

Sometimes, certain structure fields are not used, in particular for padding:

```ocaml
  [%%cstruct
  type segment = {
    gref: uint32_t;
    first_sector: uint8_t;
    last_sector: uint8_t;
    _padding: uint16_t;
  } [@@little_endian]
  ]
```

(from [mirage-block-xen](https://github.com/mirage/mirage-block-xen/blob/26b19f3f2be01c505687b3cec1666f3d4f5d73a7/lib/blkproto.ml#L303-L310))

We could detect that (if the field start with a `_`) and not emit accessor functions for this field. This can save some space in the generated code until the compiler is able to remove it.

Or is this too magical?

(in the particular case of padding, an alternative is to add a `[@pad_to 64]` attribute, but it seems a bit too specific)

**Comment by XVilka** [comment]
I agree this is a good idea. I use Cstruct a lot for parsing file formats and protocols, and it will save some code, since it is quite often you don't need every single member in the header/some entry.

**Comment by XVilka** [comment]
In the future it might be good to add an alignment attribute though, thus completely eliminating padding members.

**Comment by avsm** [comment]
Skipping underscore fields like this seems fine to me. Could also support just “_” to signify an unbound field.

**Comment by emillon** [comment]
OK! I'll prepare a PR.
