### ISSUE TITLE
ppx: duplicate fields are not detected

### ISSUE THREAD

**Issue by emillon** [mirage/ocaml-cstruct#235]
Hi,

The following piece of code is not detected as an error:

```
[%%cstruct
type dup = {
  x : uint8_t;
  x : uint8_t;
} [@@little_endian]
]
```

(both accessors with the same name are emitted).

This can happen when copy/pasting, so we might want to catch that.

Thanks!

**Comment by avsm** [comment]
Agreed, we should reject this.  If you have time to do a patch for the 4.0 bump (in #239) then this could also catch any libraries that do this in the revdeps checks for that.

**Comment by emillon** [comment]
I should be able to do that this afternoon hopefully.
