### ISSUE TITLE
Incorrect bounds-checks

### ISSUE THREAD

**Issue by talex5** [mirage/ocaml-cstruct#249]
```
$ cat test.ml 
let x = Cstruct.(BE.get_uint64 empty) 4611686018427387903

$ ocamlfind ocamlopt -linkpkg -package cstruct test.ml -o test.exe

$ ./test.exe
fish: “./test.exe” terminated by signal SIGSEGV (Address boundary error)
```

The code in cstruct was always wrong, but it turned into a segfault when https://github.com/mirage/ocaml-cstruct/pull/236 was merged.

Instead of

```ocaml
if (i+8) > t.len || i < 0 then err_invalid_bounds
```

how about

```ocaml
if i > t.len - 8 || i < 0 then err_invalid_bounds
```

`t.len - 8` won't wrap.

**Comment by dinosaure** [comment]
Note that #236 must use `caml_bigstring_set{16,32,64}u` for some atomic assumptions.

**Comment by emillon** [comment]
Interestingly, the existing fuzz tests already finds a similar one in `get_uint64`, and there are similar code paths in all getters and setters.

**Comment by talex5** [comment]
@emillon : yes, this bug was found by the fuzz tests. In previous versions, the cstruct function's check didn't raise the exception, but bigarray did, so it would still have passed the test.
