### ISSUE TITLE
Incompatible with deriving since v4.0

### ISSUE THREAD

**Issue by smolkaj** [mirage/ocaml-cstruct#260]
Since version 4.0 of cstruct, the following will no longer compile:
```
type t = Cstruct.t [@@deriving sexp]
```
The problem is that the deriver will expect functions `t_of_sexp` and `sexp_of_t` in the module `Cstruct`, but they are now located in `Cstruct_sexp`.

**Comment by hannesm** [comment]
does `type t = Cstruct_sexp.t [@@deriving sexp]` work for you? this is what I read from the 4.0.0 release notes (at https://github.com/mirage/ocaml-cstruct/releases/tag/v4.0.0)

**Comment by avsm** [comment]
Yes, you need to add `cstruct-sexp` as an opam/dune dependency, and then use `Cstruct_sexp`. Everything else should remain the same in your code as it is a type alias.

Apologies for the ugly change; this is the only way to make sexp an optional dependency at the moment. We're working on better compositional ppx mechanisms for the future.

**Comment by smolkaj** [comment]
Thanks for the quick relpy, that works. :)
(I should have realized this was the fix myself...)

**Comment by hannesm** [comment]
closing as I think there's nothing to do here. if you think the documentation / readme needs improvements, please open a PR with suggested fixes :)

**Comment by emillon** [comment]
We *could* ship something like this to point to the correct way, but I'm not sure if it's worth it:

```
(** @deprecated "<pointer to documentation>" *)
let of_sexp = `Use_cstruct_sexp_of_sexp
```

**Comment by avsm** [comment]
@emillon that's a brilliant idea.  It might still be a reasonable change to make in a point release. I'm tempted to do it for https://github.com/mirage/ocaml-uri/pull/134
