### ISSUE TITLE
ppx_cstruct testsuite broken under OCaml 4.08

### ISSUE THREAD

**Issue by gasche** [mirage/ocaml-cstruct#263]
The `ppx_cstruct` testsuite is broken under OCaml 4.08.0. See

https://github.com/ocaml/opam-repository/pull/14464
https://ci.ocaml.org/log/saved/docker-run-568738f3749bf66f881cf36d58071286/a1d58c3c528c836550875fd71cad87479128b5a4
https://github.com/gasche/opam-repository/commit/1e216a1bb02ab0573571c70d78fe5b03c6f92056

Quoting the commit message from https://github.com/gasche/opam-repository/commit/1e216a1bb02ab0573571c70d78fe5b03c6f92056

> With 4.08 the compiler prints errors differently by default,
which appears to break expect-style tests that are checking for errors.
>
> This should probably be fixed at the upstream level of dune (probably
by calling the compiler with the '-error-style short' option in
tests), so in the future (if "fixed" versions of dune are released)
the (ocaml:version < 4.08) constraint on tests should be replaced by
(dune:version >= fixed-version) to re-enable testing.

It may be enough to enable `-error-style short` or `OCAML_ERROR_STYLE=short` from the `dune` fields of the ppx_cstruct test, but I wonder if a dune-level fix would be possible.

**Comment by gasche** [comment]
(I'm not sure I have a good enough handle of the package-level vs. dune-level issue to report an issue on the Dune bugtracker right now. People that are more familiar with the mirage test setup, please feel free to give an opinion on what's the best fix and, if "upstream" is the answer, open an issue there yourself.)

**Comment by emillon** [comment]
Thanks for the report. That looked fragile indeed. Adding first class support to this in dune looks reasonable, I'll bring that up.

**Comment by avsm** [comment]
Sadly, it turns out that 4.09 has also further changed the error format, so simply setting CAML_ERROR_STYLE isn't fully sufficient. https://github.com/ocaml/opam-repository/pull/15381

(the short error style does work for 4.08 and below)
