### ISSUE TITLE
silent failure on variable/expressions in [@len]

### ISSUE THREAD

**Issue by laudecay** [mirage/ocaml-cstruct#264]
When there are fields with lengths (like `ephemeral: uint8_t [@len 32]` for example like in a cstruct), if you put a variable or an expression where the `32` is now, the ppx doesn't even give an error or complain at all, I think it just ignores the [@len ...]. 

This is pretty misleading and might be something to consider adding an error for? I just kept getting weird errors that the blit function I wanted didn't exist, and it took me a minute to trace it back to this. If someone was only using get and set this could lead to scary and difficult-to-detect memory bugs.

**Comment by emillon** [comment]
Yes, that's indeed not too great. I opened #265 to fix that. Thanks for the bug report!

**Comment by avsm** [comment]
This is fixed in cstruct 5.1.0 and higher; thanks for the report!
