### ISSUE TITLE
ppx_cstruct not supported in ocaml version 4.08 and above

### ISSUE THREAD

**Issue by bikallem** [mirage/ocaml-cstruct#274]
I get the following error when I try to use ppx_cstruct on a 4.10 codebase.
```
fatal error: exception File "hello.ml", line 70, characters 4-8: let operators are not supported before OCaml 4.08
```

**Comment by avsm** [comment]
Thanks. I was just talking to @jeremiedimino about this today. We need to upgrade the ocaml-migrate-parsetree usage to the latest version (it's still on 4.04)

**Comment by jeremiedimino** [comment]
Oh, yeah that's definitely a good reason why writing once with an old parsetree and never upgrading is not a good enough solution. In the end, we do really want to upgrade everything continously no matter what with the omp solution.

**Comment by jeremiedimino** [comment]
BTW, it might be a good occasion to switch to ppxlib :)

**Comment by avsm** [comment]
I must admit I have no idea how this works in detail! I wont have time to take a look at ppxlib until next week at the earliest. Do you fancy having a go at this @bikallem?

**Comment by bikallem** [comment]
@avsm sure I will give it a go this weekend. 👍

**Comment by avsm** [comment]
Much appreciated! Do feel free to open a WIP PR if it's helpful.

**Comment by bikallem** [comment]
PR https://github.com/mirage/ocaml-cstruct/pull/275.

**Comment by bikallem** [comment]
closing this since it is merged now.
