### ISSUE TITLE
ANSI escape sequences mess up ppx_test

### ISSUE THREAD

**Issue by sternenseemann** [mirage/ocaml-cstruct#283]
`ppx_test` will fail with diffs like this:

```
--- ppx_test/errors/cstruct_len_not_int.ml.expected     2020-10-25 18:29:59.427677585 +0000
+++ ppx_test/errors/cstruct_len_not_int.ml.errors       2020-10-25 18:30:01.067662542 +0000
@@ -1 +1 @@
-Error: ppx_cstruct: [@len] argument should be an integer
+Error: ppx_cstruct: [@len] argument should be an integer
```

where the lower `Error:` would be colored red and the upper one not.

A workaround for this I have found is using `env TERM=dumb dune runtest -p ppx_cstruct`, but I suppose this issue should be prevented somehow in the first place.

**Comment by dinosaure** [comment]
The test is reproducible with `gnome-terminal` (but it is not with `kitty`). I will try to find a solution :+1:.
