### ISSUE TITLE
Length prefixed fields and custom field types

### ISSUE THREAD

**Issue by j0sh** [mirage/ocaml-cstruct#62]
Is there any interest in having array lengths dependent on the value of a previous field, eg length prefixed structures? For example:

    cstruct string {
      uint16_t len;
      uint8_t buf[len];
    } as big_endian

While technically incompatible with pure C structs, modifying ocaml-cstruct seems like the best way to avoid writing similar binary de/serializers (I've tried! [1]).

Also, how about custom field types?

    cstruct packet {
      string data;
    } as big_endian

The ability to go wild and combine length prefixed fields with user-defined structs would also be very helpful:

    cstruct packet {
      uint8_t nb_headers;
      string headers[nb_headers];
      string data;
    } as big_endian

I'm happy to do the work if there's interest in incorporating this. Also unsure if I should base this off the ppx conversion, if/when that stabilizes.

[1] Before I realized ocaml-cstruct was a thing: https://github.com/j0sh/netser

**Comment by avsm** [comment]
Sorry about the delayed reply -- I missed this bug when you created it. I'm reluctant to add this into Cstruct, since it's meant to be a very lightweight wrapper.  Instead, it would be nicer to express more sophisticated packet parsing grammars as a GADT, and then build a staged interpreter that generates code by interpreting a packet specification.

This is roughly how the ASN.1 lib is structured, for example: https://mirage.io/blog/introducing-asn1

@yallop and @marklrh may have further thoughts on parser generators of this form.

**Comment by marklrh** [comment]
Hi, @j0sh and @avsm 

I agree Anil's idea of keeping cstruct to be a lightweight wrapper. Jeremy Yallop and I are working on a staged parser generator that that takes a protocol grammar and generates efficient parsing code. Protocol grammar can be non context-free as your example. It's interface should be very similar to [asn1-combinators](https://github.com/mirleft/ocaml-asn1-combinators). 

Also, I think GADT is just an underlying implementation that user does not know. User only needs to know how to use them, e.g. ``choice``, ``sequence``, ``left (<<)``, and ``right (>>)``. One can *use* these operations to describe grammar he wants.

p.s. thanks @avsm for that asn1 post, it is really really helpful to me :+1:

**Comment by j0sh** [comment]
@avsm Understandable, thanks for the reply and the explanation.

@marklrh is the parser generator available anywhere? Would love to test it out.

**Comment by marklrh** [comment]
@j0sh sorry it's a private repo and under heavy development. I would also love to try it out soon.
