### ISSUE TITLE
A .js subpackage?

### ISSUE THREAD

**Issue by djs55** [mirage/ocaml-cstruct#63]
I was just experimenting creating a 'tutorial' iocamljs notebook for [mirage/ocaml-vchan] in the style of [avsm/ocaml-dockerfile]. Several Mirage libraries use a small number of C bindings which would need to be implemented somewhere for javascript.

Does it make sense to create a `cstruct.js` which would contain the needed external functions?

**Comment by talex5** [comment]
Would be useful. I also defined my own versions of some of these: https://github.com/talex5/cuekeeper/blob/master/js/helpers.js
