### ISSUE TITLE
Missing API for a common idiom ?

### ISSUE THREAD

**Issue by haesbaert** [mirage/ocaml-cstruct#67]
I've recently needed to set N bytes of a Cstruct.t to a predefined value, literally just zero-out N bytes of a Cstruct.t, I could do it by creating a Bytes and doing blit_from_string, but it feels awkward.
It seems there is no straight-forward way to do it, and it seems something quite common:

This is the code in question:
```
  let pad_len = 300 - partial_len in
      let () =
        for i = 0 to pad_len do
          Cstruct.set_uint8 options_end i 0
        done
      in
      Cstruct.shift options_end pad_len
```
Is there a better way to accomplish this ? If not, would a patch to add such functionality be welcome ?

**Comment by avsm** [comment]
Would `Cstruct.memset` do the trick here?  It's new since v1.6.0, and:

```
val memset: t -> int -> unit
(** [memset t x] sets all the bytes of [t] to [x land 0xff]. *)
```

You would need to take a sub-view if you dont want the whole thing to be set, so a more optimal function could be added to avoid the intermediate allocation if it's performance critical.

**Comment by dsheets** [comment]
For clarity, the optimization you are referring to is the saving of the allocation of 3 or 4 machine words to allocate a new `Cstruct.t` cursor but not the copying or allocation of the underlying buffer. Is that correct? Is there some other allocation?

**Comment by haesbaert** [comment]
I have the same doubt also, I assume it is just the allocation of the 3 or 4 words, if the underlying buffer suffers a copy at every shift I have to rethink my approach.

The memset in my case could be used if I do a set_lenght, since the actually Cstruct is much larger than the area I want to touch. But still if this is a variable length area inside a structure.

I'm gonna close this, just wanted to be sure I wasn't missing anything.
