### ISSUE TITLE
cstruct 1.7.1 depends on sexplib < 113.01.00

### ISSUE THREAD

**Issue by artemkin** [mirage/ocaml-cstruct#79]
This dependency prevents from upgrading to Core 113.24.00. Somehow, this restriction doesn't exist in `ocaml-cstruct` repository.

See http://opam.ocaml.org/packages/cstruct/cstruct.1.7.1/

**Comment by artemkin** [comment]
I see, this is artificial restriction. 1.8.0 is in OPAM, so no issue.

**Comment by avsm** [comment]
Yes, sorry -- forgot to update this when I did the 1.8.0 release

**Comment by artemkin** [comment]
@avsm `ipaddr` and `uri` also depend on `sexplib` < 113.01.00.

**Comment by dsheets** [comment]
I can rev those this evening probably.

**Comment by artemkin** [comment]
@avsm @dsheets `ipaddr` and `uri` still limited by `sexplib`

**Comment by dsheets** [comment]
mirage/ocaml-uri#87 is waiting on CI before merge and release. `ipaddr` is underway but I haven't pushed the work yet. Sorry for the delay. :-/

**Comment by dsheets** [comment]
ipaddr 2.7.0 uses `ppx_sexp_conv` and is now available via opam. uri 1.9.2 which will also switch to `ppx_sexp_conv` is still blocked on @avsm's multi-distro CI support.
